### ISSUE TITLE
Frontend: Mail-Buttons

### ISSUE THREAD

**Issue by Zorbing** [Zorbing/polymerexpress#7]
From the specification/project description:
> Send an email to all people in one category. For example provide the first email address of
> all contacts in one category in one string seperated by a comma, ready to use in a common
> mail client.

**Comment by MTonne** [comment]
Buttons added. No functionality. List of mail addresses is missing

**Comment by Zorbing** [comment]
closed from 19e1dc8, 7e7b774 and 1a75aa1
